### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by AnnJohn** [learn-co-curriculum/javascript-logging#1]
I think the primary issue here for me is that this lesson focuses on methods but we haven't yet defined for them. And in the individual methods that are covered, things like variables and objects and errors and libraries and stack trace and arguments and object properties are mentioned but the student will have no idea what they are. 

I think this lesson is good, but might be misplaced in the track.

**Comment by jmburges** [comment]
👍  Agreed. They don't know what an object or a method is yet. 

You say to "explore" the `console`. The only code they've ever written is `console.log('hello, world')`. How would they know what methods that `console` exposes? Also they don't know what a method is yet anyway.
