### ISSUE TITLE
Readme needs to be updated to reflect changes in Chrome

### ISSUE THREAD

**Issue by kkterai** [learn-co-curriculum/javascript-logging#24]
![Screen Shot 2019-06-21 at 11 53 51 AM](https://user-images.githubusercontent.com/19792273/59945100-64f02b80-941b-11e9-8055-14e367aeb753.png)
![Screen Shot 2019-06-21 at 11 54 22 AM](https://user-images.githubusercontent.com/19792273/59945102-64f02b80-941b-11e9-9adc-d35b1d5496d0.png)

**Comment by drakeltheryuujin** [comment]
Thank you for spotting this issue and providing feedback.
We have updated the materials and believe your issue to have been resolved.
If you do not believe that this issue has been addressed, please re-open this issue. 💙
