### ISSUE TITLE
console.warn() image problem

### ISSUE THREAD

**Issue by marcbacodes** [learn-co-curriculum/javascript-logging#25]
The image for the console.warn() example isn't displayed:

![image](https://user-images.githubusercontent.com/53990623/65433940-3fa9f980-de1e-11e9-80fc-d513476c4b9b.png)

**Comment by lizbur10** [comment]
Thank you for spotting this issue and providing feedback.

We have updated the materials and believe your issue to have been resolved. 

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
